# Generated by Django 4.1.12 on 2023-11-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caringmethod',
            name='lowerAge',
        ),
        migrations.RemoveField(
            model_name='caringmethod',
            name='upperAge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diseases',
        ),
        migrations.CreateModel(
            name='UserPest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('situation', models.IntegerField()),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.pest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('situation', models.IntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.user')),
            ],
        ),
    ]
