# Generated by Django 4.1.12 on 2023-11-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0002_remove_caringmethod_lowerage_and_more'),
    ]

    operations = [
    ]
