# Generated by Django 4.1.12 on 2023-11-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0003_auto_20231122_2206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdisease',
            table='user-diseases',
        ),
        migrations.AlterModelTable(
            name='userpest',
            table='user-pests',
        ),
    ]
