# Generated by Django 4.1.12 on 2023-11-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0004_alter_userdisease_table_alter_userpest_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdisease',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='userpest',
            name='situation',
        ),
        migrations.CreateModel(
            name='LocationPest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastDate', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.location')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.pest')),
            ],
            options={
                'db_table': 'pest-disease',
            },
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastDate', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.location')),
            ],
            options={
                'db_table': 'location-disease',
            },
        ),
    ]
