# Generated by Django 4.1.12 on 2023-11-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0005_remove_userdisease_situation_and_more'),
    ]

    operations = [
    ]
