# Generated by Django 4.1.12 on 2023-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0006_auto_20231122_2232'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationpest',
            table='location-pest',
        ),
    ]
