# Generated by Django 4.1.12 on 2023-12-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0009_locationdisease_situation_locationpest_situation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdisease',
            table='user-disease',
        ),
        migrations.AlterModelTable(
            name='userpest',
            table='user-pest',
        ),
    ]
