# Generated by Django 4.1.12 on 2023-12-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0010_alter_userdisease_table_alter_userpest_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisease',
            old_name='situation',
            new_name='cases',
        ),
        migrations.RenameField(
            model_name='locationpest',
            old_name='situation',
            new_name='cases',
        ),
    ]
