# Generated by Django 4.1.12 on 2023-12-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0012_remove_locationpest_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('situation', models.IntegerField(default=0)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.pest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.user')),
            ],
            options={
                'db_table': 'user-pest',
            },
        ),
        migrations.CreateModel(
            name='UserDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('situation', models.IntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.user')),
            ],
            options={
                'db_table': 'user-disease',
            },
        ),
        migrations.CreateModel(
            name='LocationPest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastDate', models.DateField()),
                ('cases', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.location')),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.pest')),
            ],
            options={
                'db_table': 'location-pest',
            },
        ),
        migrations.CreateModel(
            name='LocationDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastDate', models.DateField()),
                ('cases', models.IntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.disease')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HybridRecommender.location')),
            ],
            options={
                'db_table': 'location-disease',
            },
        ),
    ]
