# Generated by Django 4.1.12 on 2023-12-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0013_userpest_userdisease_locationpest_locationdisease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisease',
            old_name='LastDate',
            new_name='Last_date',
        ),
        migrations.RenameField(
            model_name='locationpest',
            old_name='LastDate',
            new_name='Last_date',
        ),
        migrations.AlterModelTable(
            name='locationdisease',
            table='location_disease',
        ),
        migrations.AlterModelTable(
            name='locationpest',
            table='location_pest',
        ),
        migrations.AlterModelTable(
            name='userdisease',
            table='user_disease',
        ),
        migrations.AlterModelTable(
            name='userpest',
            table='user_pest',
        ),
    ]
