# Generated by Django 4.1.12 on 2023-12-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0014_rename_lastdate_locationdisease_last_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdisease',
            old_name='Last_date',
            new_name='last_date',
        ),
        migrations.RenameField(
            model_name='locationpest',
            old_name='Last_date',
            new_name='last_date',
        ),
    ]
