# Generated by Django 4.1.12 on 2023-12-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0016_alter_disease_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caringmethod',
            name='plantTypes',
        ),
    ]
