# Generated by Django 4.1.12 on 2024-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HybridRecommender', '0017_remove_caringmethod_planttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdisease',
            name='entered_symptoms',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpest',
            name='entered_symptoms',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
